//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WSSancor.WSTarifas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProxyTarifasSoap", Namespace="http://tempuri.org/")]
    public partial class ProxyTarifas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TarifarPMXOperationCompleted;
        
        private System.Threading.SendOrPostCallback TarifarARTOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarProvinciasOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarModulosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProxyTarifas() {
            this.Url = global::WSSancor.Properties.Settings.Default.WSSancor_WSTarifas_ProxyTarifas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TarifarPMXCompletedEventHandler TarifarPMXCompleted;
        
        /// <remarks/>
        public event TarifarARTCompletedEventHandler TarifarARTCompleted;
        
        /// <remarks/>
        public event RecuperarProvinciasCompletedEventHandler RecuperarProvinciasCompleted;
        
        /// <remarks/>
        public event RecuperarModulosCompletedEventHandler RecuperarModulosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TarifarPMX", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CotizacionGSS TarifarPMX(long cuitEmpresa, string razonSocial, int codActividad, int cantTrabajadores, decimal masaSalarial, byte codProvinciaRiesgo, byte codModuloRC, byte codModuloAP) {
            object[] results = this.Invoke("TarifarPMX", new object[] {
                        cuitEmpresa,
                        razonSocial,
                        codActividad,
                        cantTrabajadores,
                        masaSalarial,
                        codProvinciaRiesgo,
                        codModuloRC,
                        codModuloAP});
            return ((CotizacionGSS)(results[0]));
        }
        
        /// <remarks/>
        public void TarifarPMXAsync(long cuitEmpresa, string razonSocial, int codActividad, int cantTrabajadores, decimal masaSalarial, byte codProvinciaRiesgo, byte codModuloRC, byte codModuloAP) {
            this.TarifarPMXAsync(cuitEmpresa, razonSocial, codActividad, cantTrabajadores, masaSalarial, codProvinciaRiesgo, codModuloRC, codModuloAP, null);
        }
        
        /// <remarks/>
        public void TarifarPMXAsync(long cuitEmpresa, string razonSocial, int codActividad, int cantTrabajadores, decimal masaSalarial, byte codProvinciaRiesgo, byte codModuloRC, byte codModuloAP, object userState) {
            if ((this.TarifarPMXOperationCompleted == null)) {
                this.TarifarPMXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTarifarPMXOperationCompleted);
            }
            this.InvokeAsync("TarifarPMX", new object[] {
                        cuitEmpresa,
                        razonSocial,
                        codActividad,
                        cantTrabajadores,
                        masaSalarial,
                        codProvinciaRiesgo,
                        codModuloRC,
                        codModuloAP}, this.TarifarPMXOperationCompleted, userState);
        }
        
        private void OnTarifarPMXOperationCompleted(object arg) {
            if ((this.TarifarPMXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TarifarPMXCompleted(this, new TarifarPMXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TarifarART", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Alicuota TarifarART(long cuitEmpresa, int codActividad, int cantTrabajadores, decimal masaSalarial, short codPostal) {
            object[] results = this.Invoke("TarifarART", new object[] {
                        cuitEmpresa,
                        codActividad,
                        cantTrabajadores,
                        masaSalarial,
            codPostal});
            return ((Alicuota)(results[0]));
        }
        
        /// <remarks/>
        public void TarifarARTAsync(long cuitEmpresa, int codActividad, int cantTrabajadores, decimal masaSalarial) {
            this.TarifarARTAsync(cuitEmpresa, codActividad, cantTrabajadores, masaSalarial, null);
        }
        
        /// <remarks/>
        public void TarifarARTAsync(long cuitEmpresa, int codActividad, int cantTrabajadores, decimal masaSalarial, object userState) {
            if ((this.TarifarARTOperationCompleted == null)) {
                this.TarifarARTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTarifarARTOperationCompleted);
            }
            this.InvokeAsync("TarifarART", new object[] {
                        cuitEmpresa,
                        codActividad,
                        cantTrabajadores,
                        masaSalarial}, this.TarifarARTOperationCompleted, userState);
        }
        
        private void OnTarifarARTOperationCompleted(object arg) {
            if ((this.TarifarARTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TarifarARTCompleted(this, new TarifarARTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarProvincias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProvinciaRiesgo[] RecuperarProvincias() {
            object[] results = this.Invoke("RecuperarProvincias", new object[0]);
            return ((ProvinciaRiesgo[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarProvinciasAsync() {
            this.RecuperarProvinciasAsync(null);
        }
        
        /// <remarks/>
        public void RecuperarProvinciasAsync(object userState) {
            if ((this.RecuperarProvinciasOperationCompleted == null)) {
                this.RecuperarProvinciasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarProvinciasOperationCompleted);
            }
            this.InvokeAsync("RecuperarProvincias", new object[0], this.RecuperarProvinciasOperationCompleted, userState);
        }
        
        private void OnRecuperarProvinciasOperationCompleted(object arg) {
            if ((this.RecuperarProvinciasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarProvinciasCompleted(this, new RecuperarProvinciasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarModulos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Modulo[] RecuperarModulos(byte codServicio) {
            object[] results = this.Invoke("RecuperarModulos", new object[] {
                        codServicio});
            return ((Modulo[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarModulosAsync(byte codServicio) {
            this.RecuperarModulosAsync(codServicio, null);
        }
        
        /// <remarks/>
        public void RecuperarModulosAsync(byte codServicio, object userState) {
            if ((this.RecuperarModulosOperationCompleted == null)) {
                this.RecuperarModulosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarModulosOperationCompleted);
            }
            this.InvokeAsync("RecuperarModulos", new object[] {
                        codServicio}, this.RecuperarModulosOperationCompleted, userState);
        }
        
        private void OnRecuperarModulosOperationCompleted(object arg) {
            if ((this.RecuperarModulosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarModulosCompleted(this, new RecuperarModulosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CotizacionGSS {
        
        private int nroCotizacionField;
        
        private long cuitEmpresaField;
        
        private Actividad actividadField;
        
        private decimal masaSalarialField;
        
        private int cantTrabajadoresField;
        
        private ProvinciaRiesgo provinciaField;
        
        private Intermediario intermediarioField;
        
        private short nroLegajoAltaField;
        
        private System.DateTime fechaAltaField;
        
        private System.Nullable<short> nroLegajoBajaField;
        
        private System.Nullable<System.DateTime> fechaBajaField;
        
        private short nroLegajoABMField;
        
        private System.DateTime fechaABMField;
        
        private CotizacionProductoGSS[] productosField;
        
        /// <remarks/>
        public int NroCotizacion {
            get {
                return this.nroCotizacionField;
            }
            set {
                this.nroCotizacionField = value;
            }
        }
        
        /// <remarks/>
        public long CuitEmpresa {
            get {
                return this.cuitEmpresaField;
            }
            set {
                this.cuitEmpresaField = value;
            }
        }
        
        /// <remarks/>
        public Actividad Actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
            }
        }
        
        /// <remarks/>
        public decimal MasaSalarial {
            get {
                return this.masaSalarialField;
            }
            set {
                this.masaSalarialField = value;
            }
        }
        
        /// <remarks/>
        public int CantTrabajadores {
            get {
                return this.cantTrabajadoresField;
            }
            set {
                this.cantTrabajadoresField = value;
            }
        }
        
        /// <remarks/>
        public ProvinciaRiesgo Provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
            }
        }
        
        /// <remarks/>
        public Intermediario Intermediario {
            get {
                return this.intermediarioField;
            }
            set {
                this.intermediarioField = value;
            }
        }
        
        /// <remarks/>
        public short NroLegajoAlta {
            get {
                return this.nroLegajoAltaField;
            }
            set {
                this.nroLegajoAltaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaAlta {
            get {
                return this.fechaAltaField;
            }
            set {
                this.fechaAltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> NroLegajoBaja {
            get {
                return this.nroLegajoBajaField;
            }
            set {
                this.nroLegajoBajaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaBaja {
            get {
                return this.fechaBajaField;
            }
            set {
                this.fechaBajaField = value;
            }
        }
        
        /// <remarks/>
        public short NroLegajoABM {
            get {
                return this.nroLegajoABMField;
            }
            set {
                this.nroLegajoABMField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaABM {
            get {
                return this.fechaABMField;
            }
            set {
                this.fechaABMField = value;
            }
        }
        
        /// <remarks/>
        public CotizacionProductoGSS[] Productos {
            get {
                return this.productosField;
            }
            set {
                this.productosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Actividad {
        
        private int codActividadField;
        
        private string descripcionField;
        
        private byte codSemaforoField;
        
        private bool requierePreviaField;
        
        /// <remarks/>
        public int CodActividad {
            get {
                return this.codActividadField;
            }
            set {
                this.codActividadField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public byte CodSemaforo {
            get {
                return this.codSemaforoField;
            }
            set {
                this.codSemaforoField = value;
            }
        }
        
        /// <remarks/>
        public bool RequierePrevia {
            get {
                return this.requierePreviaField;
            }
            set {
                this.requierePreviaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Alicuota {
        
        private int codActividadField;
        
        private int cantTrabajadoresField;
        
        private decimal masaSalarialField;
        
        private decimal montoFijoField;
        
        private decimal porcVariableField;
        
        private string descripcionField;
        
        /// <remarks/>
        public int CodActividad {
            get {
                return this.codActividadField;
            }
            set {
                this.codActividadField = value;
            }
        }
        
        /// <remarks/>
        public int CantTrabajadores {
            get {
                return this.cantTrabajadoresField;
            }
            set {
                this.cantTrabajadoresField = value;
            }
        }
        
        /// <remarks/>
        public decimal MasaSalarial {
            get {
                return this.masaSalarialField;
            }
            set {
                this.masaSalarialField = value;
            }
        }
        
        /// <remarks/>
        public decimal MontoFijo {
            get {
                return this.montoFijoField;
            }
            set {
                this.montoFijoField = value;
            }
        }
        
        /// <remarks/>
        public decimal PorcVariable {
            get {
                return this.porcVariableField;
            }
            set {
                this.porcVariableField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Modulo {
        
        private byte codModuloField;
        
        private string descModuloField;
        
        private decimal sumaAseguradaField;
        
        /// <remarks/>
        public byte CodModulo {
            get {
                return this.codModuloField;
            }
            set {
                this.codModuloField = value;
            }
        }
        
        /// <remarks/>
        public string DescModulo {
            get {
                return this.descModuloField;
            }
            set {
                this.descModuloField = value;
            }
        }
        
        /// <remarks/>
        public decimal SumaAsegurada {
            get {
                return this.sumaAseguradaField;
            }
            set {
                this.sumaAseguradaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CotizacionProductoGSS {
        
        private short nBranchField;
        
        private short nProductField;
        
        private short productIdField;
        
        private Modulo moduloField;
        
        private decimal montoFijoField;
        
        private decimal porcVariableField;
        
        private decimal costoField;
        
        private decimal tasaField;
        
        private bool errorField;
        
        private string descripcionField;
        
        /// <remarks/>
        public short nBranch {
            get {
                return this.nBranchField;
            }
            set {
                this.nBranchField = value;
            }
        }
        
        /// <remarks/>
        public short nProduct {
            get {
                return this.nProductField;
            }
            set {
                this.nProductField = value;
            }
        }
        
        /// <remarks/>
        public short ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public Modulo Modulo {
            get {
                return this.moduloField;
            }
            set {
                this.moduloField = value;
            }
        }
        
        /// <remarks/>
        public decimal MontoFijo {
            get {
                return this.montoFijoField;
            }
            set {
                this.montoFijoField = value;
            }
        }
        
        /// <remarks/>
        public decimal PorcVariable {
            get {
                return this.porcVariableField;
            }
            set {
                this.porcVariableField = value;
            }
        }
        
        /// <remarks/>
        public decimal Costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Tasa {
            get {
                return this.tasaField;
            }
            set {
                this.tasaField = value;
            }
        }
        
        /// <remarks/>
        public bool Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Intermediario {
        
        private byte nroEmpsocField;
        
        private byte tipoPersonaField;
        
        private int nroPersonaField;
        
        private int nIntermedField;
        
        /// <remarks/>
        public byte NroEmpsoc {
            get {
                return this.nroEmpsocField;
            }
            set {
                this.nroEmpsocField = value;
            }
        }
        
        /// <remarks/>
        public byte TipoPersona {
            get {
                return this.tipoPersonaField;
            }
            set {
                this.tipoPersonaField = value;
            }
        }
        
        /// <remarks/>
        public int NroPersona {
            get {
                return this.nroPersonaField;
            }
            set {
                this.nroPersonaField = value;
            }
        }
        
        /// <remarks/>
        public int nIntermed {
            get {
                return this.nIntermedField;
            }
            set {
                this.nIntermedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProvinciaRiesgo {
        
        private byte codPciaField;
        
        private string nombrePciaField;
        
        /// <remarks/>
        public byte CodPcia {
            get {
                return this.codPciaField;
            }
            set {
                this.codPciaField = value;
            }
        }
        
        /// <remarks/>
        public string NombrePcia {
            get {
                return this.nombrePciaField;
            }
            set {
                this.nombrePciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void TarifarPMXCompletedEventHandler(object sender, TarifarPMXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TarifarPMXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TarifarPMXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CotizacionGSS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CotizacionGSS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void TarifarARTCompletedEventHandler(object sender, TarifarARTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TarifarARTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TarifarARTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alicuota Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alicuota)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RecuperarProvinciasCompletedEventHandler(object sender, RecuperarProvinciasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarProvinciasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarProvinciasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProvinciaRiesgo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProvinciaRiesgo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RecuperarModulosCompletedEventHandler(object sender, RecuperarModulosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarModulosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarModulosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Modulo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Modulo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591